
{{- if .Values.bot.disruption }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bot.fullname" . }}-proxy
  labels:
    {{- include "bot.labels" . | nindent 4 }}
  {{- with .Values.bot.disruption.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}


spec:
  {{- with .Values.bot.disruption.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}

  {{- with .Values.bot.disruption.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}

  selector:
    matchLabels:
      component: bot
      {{- include "bot.selectorLabels" . | nindent 4 }}
      {{- with .Values.bot.extraLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
