{{ if and .Values.bot.enabled .Values.bot.extraRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "bot.fullname" . }}
  labels:
    {{- include "bot.labels" . | nindent 4 }}
  {{- with .Values.bot.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{- with .Values.bot.extraRole.rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}


{{ end }}
