{{ if and .Values.bot.enabled .Values.bot.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bot.bot.serviceAccountName" . }}
  labels:
    component: bot
    {{- include "bot.labels" . | nindent 4 }}
    {{- with .Values.bot.serviceAccount.extraLabels }}
      {{- toYaml . | nindent 8 }}
    {{- end }}

  {{- with .Values.bot.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{ end }}
