{{ if and .Values.bot.enabled .Values.bot.service.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "bot.fullname" . }}-headless
  labels:
    {{- include "bot.labels" . | nindent 4 }}
  {{- with .Values.bot.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: "None"

  ports:
  {{ range $key, $value := .Values.bot.service.ports }}
    - name: {{ $value.name }}
      port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}

      {{- with $value.protocol }}
      protocol: {{ . }}
      {{- end }}

      {{- if and ($value.nodePort) (eq ($.Values.bot.service.type | toString) "NodePort") }}
      nodePort: {{ $value.nodePort }}
      {{- end }}
  {{- end}}

  selector:
    component: bot
    {{- include "bot.selectorLabels" . | nindent 4 }}
    {{- with .Values.bot.extraLabels }}
    {{- toYaml . | nindent 8 }}
    {{- end }}

{{- end }}
